version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data/

  migrate:
    image: migrate/migrate
    entrypoint: ["/bin/sh", "-c", "migrate -path repository/postgres/migrations -database postgres://$DB_USER:$DB_PASS@postgres:5432/$DB_NAME up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

  nginx:
    image: nginx:stable-alpine3.17-slim
    depends_on:
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8000:80"

  redis:
    image: redis:7

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgresdata:
    driver: local
